Documentation additions
hive-keychain/hive-keychain-extension pull request #288
Opened 2022-07-27 14:00 UTC by npfedwards

Putting this here as a bit of a work in progress for a bit of feedback before I add to it further.

I've added a couple of examples to the docblocks and changed the callback param to a callback type rather than function.

2022-07-27 18:08 UTC, npfedwards commented
What does `requestHandshake` actually do? The callback seems to have no parameters to give me details on the current installation and if the hive_keychain object isn't there then we'd get an undefined error anyway.

I tested it with
```js
keychain.requestHandshake((response) => {
    console.log(response);
});```

2022-08-03 11:11 UTC, stoodkev commented
> What does `requestHandshake` actually do? The callback seems to have no parameters to give me details on the current installation and if the hive_keychain object isn't there then we'd get an undefined error anyway.
> 
> I tested it with
> 
> ```js
> keychain.requestHandshake((response) => {
>     console.log(response);
> });```
> ```

It's just there to make sure that Keychain is there and working properly.

2022-08-22 08:14 UTC, cedricguillas commented on documentation/README.md
> +*   `callback` **[requestCallback][96]** Function that handles keychain's response to the request
Can you put a capital K to Keychain to people don't get confused

2022-08-22 08:15 UTC, cedricguillas commented on documentation/README.md
> +*   `callback` **[requestCallback][96]** Function that handles keychain's response to the request
same here

2022-08-22 08:16 UTC, cedricguillas commented on documentation/README.md
> +keychain.requestAddAccountAuthority(username, 'stoodkev', 'Active', 2, (response) => {
Maybe change 'username' to account ? Or something more explicit to show that it is the account that will give the authorization

2022-08-22 08:17 UTC, cedricguillas commented on documentation/README.md
> +*   `callback` **[requestCallback][96]** Function that handles keychain's response to the request
same here

2022-08-22 08:23 UTC, cedricguillas commented on documentation/README.md
> +  keychain.requestProxy(username, username, '5.000', (response) => {
probably powerDown :)

2022-08-22 08:23 UTC, cedricguillas commented on documentation/README.md
> +  keychain.requestProxy(username, '5.000', (response) => {
probably powerDown

2022-08-22 08:25 UTC, cedricguillas commented on documentation/README.md
> +##### Examples
maybe here you could add an example of how to remove the vote from a proposal ?

2022-08-22 08:27 UTC, cedricguillas commented on documentation/README.md
> +*   `recurrence` **[Number][98]** How often will the payment be triggered (in hours).
you can add the minimum for those parameters : 
- recurrence has to be minimum 24
- executions has to be minimum 2

2022-08-22 08:29 UTC, cedricguillas requested changes
I added some comments, please check them before we can merge. Thank you :)

2022-08-22 08:57 UTC, cedricguillas approved these changes

2022-09-12 03:47 UTC, stoodkev approved these changes

2022-09-12 03:48 UTC, stoodkev commented
Thanks for your contribution @npfedwards

2022-09-12 03:48 UTC, merged