Feature/page authorities visualization management 860q6tyq2
hive-keychain/hive-keychain-extension pull request #416
Opened 2023-04-05 15:50 UTC by theghost1980

2023-04-05 23:51 UTC, cedricguillas commented on src/popup/pages/app-container/settings/accounts/manage-account-authorities/manage-account-authorities.component.scss
> +  overflow-x: hidden;
why do we need to specify overflow-x ?

2023-04-05 23:57 UTC, cedricguillas reviewed
please check the comments

2023-04-06 13:09 UTC, theghost1980 commented on src/popup/pages/app-container/settings/accounts/manage-account-authorities/manage-account-authorities.component.scss
> +  overflow-x: hidden;
removed :)

2023-04-20 03:16 UTC, stoodkev requested changes
Please change the following : 
- Remove weight and threshold. Having there is weird since we only put the authorities and not the keys.
- Change `Key` by `Authority` in `Posting/Active Key`
- If there's no Posting Authority hide the section, same for active
- If neither posting or active authority : "No authority has been given to other accounts"

2023-05-04 06:40 UTC, cedricguillas approved these changes

2023-05-04 06:50 UTC, merged